<?php

return array(
    '5.3' => array(
        'call_user_method' => true,
        'call_user_method_array' => true,
        'define_syslog_variables' => true,
        'dl' => true,
        'set_magic_quotes_runtime' => true,
        'session_register' => true,
        'session_unregister' => true,
        'session_is_registered' => true,
        'set_socket_blocking' => true,
        'mysql_db_query' => true,
        'mysql_escape_string' => true,
    ),
    '5.4' => array(
        'hex2bin' => true,
        'http_response_code' => true,
        'get_declared_traits' => true,
        'getimagesizefromstring' => true,
        'stream_set_chunk_size' => true,
        'socket_import_stream' => true,
        'trait_exists' => true,
        'header_register_callback' => true,
        // SPL
        'class_uses' => true,
        // Session
        'session_status' => true,
        'session_register_shutdown' => true,
        // Mysqli
        'mysqli_error_list' => true,
        'mysqli_stmt_error_list' => true,
        // Libxml
        'libxml_set_external_entity_loader' => true,
        // LDAP
        'ldap_control_paged_result' => true,
        'ldap_control_paged_result_response' => true,
        // Intl
        'transliterator_create' => true,
        'transliterator_create_from_rules' => true,
        'transliterator_create_inverse' => true,
        'transliterator_get_error_code' => true,
        'transliterator_get_error_message' => true,
        'transliterator_list_ids' => true,
        'transliterator_transliterate' => true,
        // Zlib
        'zlib_decode' => true,
        'zlib_encode' => true,
    ),
    '5.5' => array(
        // PHP Core
        'boolval' => true,
        'password_get_info' => true,
        'password_hash' => true,
        'password_needs_rehash' => true,
        'password_verify' => true,
        'array_column' => true,

        // curl
        'curl_escape' => true,
        'curl_multi_setopt' => true,
        'curl_multi_strerror curl_pause' => true,
        'curl_reset' => true,
        'curl_share_close' => true,
        'curl_share_init' => true,
        'curl_share_setopt curl_strerror and curl_unescape' => true,

        // Hash
        'hash_pbkdf2' => true,

        // GD
        'imageaffinematrixconcat' => true,
        'imageaffinematrixget' => true,
        'imagecrop' => true,
        'imagecropauto' => true,
        'imageflip' => true,
        'imagepalettetotruecolor' => true,
        'imagescale' => true,

        // Intl
        'datefmt_format_object' => true,
        'datefmt_get_calendar_object' => true,
        'datefmt_get_timezone' => true,
        'datefmt_set_timezone' => true,
        'datefmt_get_calendar_object' => true,
        'intlcal_create_instance' => true,
        'intlcal_get_keyword_values_for_locale' => true,
        'intlcal_get_now' => true,
        'intlcal_get_available_locales' => true,
        'intlcal_get' => true,
        'intlcal_get_time' => true,
        'intlcal_set_time' => true,
        'intlcal_add' => true,
        'intlcal_set_time_zone' => true,
        'intlcal_after' => true,
        'intlcal_before' => true,
        'intlcal_set' => true,
        'intlcal_roll' => true,
        'intlcal_clear' => true,
        'intlcal_field_difference' => true,
        'intlcal_get_actual_maximum' => true,
        'intlcal_get_actual_minimum' => true,
        'intlcal_get_day_of_week_type' => true,
        'intlcal_get_first_day_of_week' => true,
        'intlcal_get_greatest_minimum' => true,
        'intlcal_get_least_maximum' => true,
        'intlcal_get_locale' => true,
        'intlcal_get_maximum' => true,
        'intlcal_get_minimal_days_in_first_week' => true,
        'intlcal_get_minimum' => true,
        'intlcal_get_time_zone' => true,
        'intlcal_get_type' => true,
        'intlcal_get_weekend_transition' => true,
        'intlcal_in_daylight_time' => true,
        'intlcal_is_equivalent_to' => true,
        'intlcal_is_lenient' => true,
        'intlcal_is_set' => true,
        'intlcal_is_weekend' => true,
        'intlcal_set_first_day_of_week' => true,
        'intlcal_set_lenient' => true,
        'intlcal_equals' => true,
        'intlcal_get_repeated_wall_time_option' => true,
        'intlcal_get_skipped_wall_time_option' => true,
        'intlcal_set_repeated_wall_time_option' => true,
        'intlcal_set_skipped_wall_time_option' => true,
        'intlcal_from_date_time' => true,
        'intlcal_to_date_time' => true,
        'intlcal_get_error_code' => true,
        'intlcal_get_error_message' => true,
        'intlgregcal_create_instance' => true,
        'intlgregcal_set_gregorian_change' => true,
        'intlgregcal_get_gregorian_change' => true,
        'intlgregcal_is_leap_year' => true,
        'intltz_create_time_zone' => true,
        'intltz_create_default' => true,
        'intltz_get_id' => true,
        'intltz_get_gmt' => true,
        'intltz_get_unknown' => true,
        'intltz_create_enumeration' => true,
        'intltz_count_equivalent_ids' => true,
        'intltz_create_time_zone_id_enumeration' => true,
        'intltz_get_canonical_id' => true,
        'intltz_get_region' => true,
        'intltz_get_tz_data_version' => true,
        'intltz_get_equivalent_id' => true,
        'intltz_use_daylight_time' => true,
        'intltz_get_offset' => true,
        'intltz_get_raw_offset' => true,
        'intltz_has_same_rules' => true,
        'intltz_get_display_name' => true,
        'intltz_get_dst_savings' => true,
        'intltz_from_date_time_zone' => true,
        'intltz_to_date_time_zone' => true,
        'intltz_get_error_code' => true,
        'intltz_get_error_message' => true,
    ),
    '5.5.1' => array(
        'intlcal_set_minimal_days_in_first_week' => true,

        // mysqli
        'mysqli_begin_transaction' => true,
        'mysqli_savepoint' => true,
        'mysqli_release_savepoint' => true,

        // mysqlnd
        'mysqlnd_savepoint' => true,
        'mysqlnd_release_savepoint' => true,

        // pgsql
        'pg_escape_literal' => true,
        'pg_escape_identifier' => true,

        // socket
        'socket_cmsg_space' => true,
        'socket_sendmsg' => true,
        'socket_recvmsg' => true,
    ),
    '5.5.4' => array(
        'opcache_compile_file' => true,
    )
);
